name: build and publish

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: deploy to netlify
        env:
          token: ${{ secrets.NETLIFY_API_TOKEN }}
          siteId: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npx @11ty/eleventy
          netlify deploy \
            --site=${{ env.siteId }} \
            --auth=${{ env.token }} \
            --prod
